name: learn-github-actions
run-name: ${{ github.run_id }} is learning GitHub Actions
on:
  push:
    branches:
      - 'feature/**'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "hello world"
