name: Java CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      # generates coverage-report.md and publishes as checkrun
#      - name: JaCoCo Code Coverage Report
#        id: jacoco_reporter
#        uses: PavanMudigonda/jacoco-reporter@v4.8
#        with:
#          coverage_results_path: jacoco-report/test.xml
#          coverage_report_name: Coverage
#          coverage_report_title: JaCoCo
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          skip_check_run: false
#          minimum_coverage: 80
#          fail_below_threshold: false
#          publish_only_summary: false

      # Publish Coverage Job Summary  # Optional
      - name: Add Coverage Job Summary
        run: ls -al && pwd

